### ISSUE TITLE
Security issue in !gcode command

### ISSUE THREAD

**Issue by hgross** [hetile1/3DM-Bot#23]
Hi, 

this line 
https://github.com/hetile1/3DM-Bot/blob/76c3e40459fcc0c74b4c27d204c34132f46b6f30/3dm.py#L615
is a severe security issue. You should check and properly escape the "search" input.
It is probably easier and more secure to just do the parsing directly in python instead of using a shell subprocess. 

For example: `!gcode G0 && reboot && ` will reboot your host.
Also works with `!gcode G0 && curl http://some-url && ` and more ...

**Comment by hetile1** [comment]
Fixed in this PR https://github.com/hetile1/3DM-Bot/pull/26
